import {
  fetchBaseQuery,
  createApi,
  BaseQueryFn,
} from '@reduxjs/toolkit/query/react';
import { BASE_URL } from '../constants';

// Define the base query
const baseQuery: BaseQueryFn = fetchBaseQuery({
  baseUrl: BASE_URL,
});

// Define the API slice
export const apiSlice = createApi({
  reducerPath: 'api', // Optional: specify a custom reducer path
  baseQuery,
  tagTypes: ['Product', 'Order', 'User'],
  endpoints: (builder) => ({}),
});

// Optional: Export hooks generated by createApi
// export const { useLazyQuery, useQuery, useMutation } = apiSlice;
